<?php
require __DIR__ . '/vendor/composer/autoload_psr4.php';

// Get the existing prefixes from autoload_psr4 (which we already fixed)
$prefixDirsPsr4 = require __DIR__ . '/vendor/composer/autoload_psr4.php';

// Get classmap
$classMap = require __DIR__ . '/vendor/composer/autoload_classmap.php';

// Get fallback dirs and psr4
$fallbackDirsPsr4 = require __DIR__ . '/vendor/composer/autoload_psr4.php'; // already have it

// Build the static autoload file content
$content = '<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit53b5d56b3b7e3cbac1713e68c8850f6c
{
    public static $prefixLengthsPsr4 = array (
';

// Calculate prefix lengths
foreach ($prefixDirsPsr4 as $prefix => $dirs) {
    $content .= "        '" . addslashes($prefix) . "' => " . strlen($prefix) . ",\n";
}

$content .= "    );\n\n";
$content .= '    public static $prefixDirsPsr4 = ' . var_export($prefixDirsPsr4, true) . ";\n\n";
$content .= '    public static $classMap = ' . var_export($classMap, true) . ";\n\n";

$content .= <<<'PHP'
    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit53b5d56b3b7e3cbac1713e68c8850f6c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit53b5d56b3b7e3cbac1713e68c8850f6c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit53b5d56b3b7e3cbac1713e68c8850f6c::$classMap;
        }, null, ClassLoader::class);
    }
}
PHP;

file_put_contents(__DIR__ . '/vendor/composer/autoload_static.php', $content);
echo "Done\n";
