import AdminLayouts from '@/Layouts/AdminLayouts';
import { Head, Link, router, usePage } from '@inertiajs/react';
import { useState } from 'react';
import {
    FileText, Download, RefreshCw, Trash2, Plus,
    Search, CheckCircle, XCircle, AlertCircle,
    Eye, Printer, FileDown, Clock, User,
    ChevronRight, Filter
} from 'lucide-react';

export default function AdminResumes({ resumes, jobSeekersWithoutResume, templates }) {
    const { flash } = usePage().props;
    const [searchTerm, setSearchTerm] = useState('');
    const [showGenerateModal, setShowGenerateModal] = useState(false);
    const [selectedSeekerId, setSelectedSeekerId] = useState('');
    const [generating, setGenerating] = useState(false);

    const filteredResumes = resumes?.data?.filter(r =>
        !searchTerm ||
        r.resume_id?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        r.job_seeker?.first_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        r.job_seeker?.last_name?.toLowerCase().includes(searchTerm.toLowerCase())
    ) ?? [];

    const handleGenerate = async (e) => {
        e.preventDefault();
        if (!selectedSeekerId) return;
        setGenerating(true);
        router.post(route('admin.resumes.generate'), {
            job_seeker_id: selectedSeekerId,
        }, {
            onFinish: () => { setGenerating(false); setShowGenerateModal(false); setSelectedSeekerId(''); },
        });
    };

    return (
        <AdminLayouts
            header={<h2 className="text-xl font-semibold leading-tight text-gray-800">Resume Management</h2>}
        >
            <Head title="Resume Management" />
            <div className="py-8">
                <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                    {flash?.success && (
                        <div className="mb-4 rounded-lg bg-green-50 border border-green-200 p-4 text-sm text-green-700 flex items-center gap-2">
                            <CheckCircle className="h-4 w-4" /> {flash.success}
                        </div>
                    )}
                    {flash?.error && (
                        <div className="mb-4 rounded-lg bg-red-50 border border-red-200 p-4 text-sm text-red-700 flex items-center gap-2">
                            <XCircle className="h-4 w-4" /> {flash.error}
                        </div>
                    )}

                    <div className="mb-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                        <div className="relative w-full sm:w-72">
                            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                            <input
                                type="text"
                                placeholder="Search resumes..."
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                                className="w-full rounded-lg border border-slate-300 pl-9 pr-4 py-2 text-sm focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
                            />
                        </div>
                        <button
                            onClick={() => setShowGenerateModal(true)}
                            className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 transition-colors"
                        >
                            <Plus className="h-4 w-4" /> Generate Resume
                        </button>
                    </div>

                    <div className="rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden">
                        <div className="overflow-x-auto">
                            <table className="w-full text-sm">
                                <thead>
                                    <tr className="border-b border-slate-200 bg-slate-50">
                                        <th className="px-4 py-3 text-left font-semibold text-slate-600">Resume ID</th>
                                        <th className="px-4 py-3 text-left font-semibold text-slate-600">Job Seeker</th>
                                        <th className="px-4 py-3 text-left font-semibold text-slate-600">Template</th>
                                        <th className="px-4 py-3 text-left font-semibold text-slate-600">Status</th>
                                        <th className="px-4 py-3 text-left font-semibold text-slate-600">Generated By</th>
                                        <th className="px-4 py-3 text-left font-semibold text-slate-600">Date</th>
                                        <th className="px-4 py-3 text-right font-semibold text-slate-600">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {filteredResumes.length === 0 && (
                                        <tr>
                                            <td colSpan={7} className="px-4 py-12 text-center text-slate-500">
                                                <FileText className="mx-auto h-8 w-8 mb-2 opacity-50" />
                                                <p>No resumes found</p>
                                            </td>
                                        </tr>
                                    )}
                                    {filteredResumes.map((resume) => (
                                        <tr key={resume.id} className="border-b border-slate-100 hover:bg-slate-50 transition-colors">
                                            <td className="px-4 py-3">
                                                <span className="font-mono text-xs font-medium text-blue-600 bg-blue-50 px-2 py-1 rounded">
                                                    {resume.resume_id}
                                                </span>
                                            </td>
                                            <td className="px-4 py-3">
                                                <div className="flex items-center gap-2">
                                                    <div className="h-8 w-8 rounded-full bg-blue-100 flex items-center justify-center text-xs font-bold text-blue-700">
                                                        {(resume.job_seeker?.first_name?.[0] ?? '?')}
                                                    </div>
                                                    <div>
                                                        <p className="font-medium text-slate-900">
                                                            {resume.job_seeker?.first_name} {resume.job_seeker?.last_name}
                                                        </p>
                                                        <p className="text-xs text-slate-500">{resume.job_seeker?.email}</p>
                                                    </div>
                                                </div>
                                            </td>
                                            <td className="px-4 py-3">
                                                <span className="text-slate-700">{templates[resume.template] ?? resume.template}</span>
                                            </td>
                                            <td className="px-4 py-3">
                                                {resume.status === 'ready_for_download' ? (
                                                    <span className="inline-flex items-center gap-1 rounded-full bg-green-50 px-2.5 py-0.5 text-xs font-medium text-green-700">
                                                        <CheckCircle className="h-3 w-3" /> Ready
                                                    </span>
                                                ) : (
                                                    <span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2.5 py-0.5 text-xs font-medium text-amber-700">
                                                        <Clock className="h-3 w-3" /> {resume.status}
                                                    </span>
                                                )}
                                            </td>
                                            <td className="px-4 py-3 text-slate-600">
                                                {resume.generated_by?.name ?? 'N/A'}
                                            </td>
                                            <td className="px-4 py-3 text-slate-500 text-xs">
                                                {resume.generated_at ? new Date(resume.generated_at).toLocaleDateString() : 'N/A'}
                                            </td>
                                            <td className="px-4 py-3">
                                                <div className="flex items-center justify-end gap-1">
                                                    <Link
                                                        href={route('admin.resumes.download', resume.id)}
                                                        className="p-1.5 rounded-lg text-slate-500 hover:text-blue-600 hover:bg-blue-50 transition-colors"
                                                        title="Download PDF"
                                                    >
                                                        <Download className="h-4 w-4" />
                                                    </Link>
                                                    <Link
                                                        href={route('admin.resumes.regenerate', resume.id)}
                                                        method="post"
                                                        as="button"
                                                        className="p-1.5 rounded-lg text-slate-500 hover:text-amber-600 hover:bg-amber-50 transition-colors"
                                                        title="Regenerate"
                                                    >
                                                        <RefreshCw className="h-4 w-4" />
                                                    </Link>
                                                    <Link
                                                        href={route('admin.resumes.delete', resume.id)}
                                                        method="delete"
                                                        as="button"
                                                        className="p-1.5 rounded-lg text-slate-500 hover:text-red-600 hover:bg-red-50 transition-colors"
                                                        title="Delete"
                                                        onClick={(e) => !confirm('Delete this resume?') && e.preventDefault()}
                                                    >
                                                        <Trash2 className="h-4 w-4" />
                                                    </Link>
                                                </div>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>

                        {resumes?.links && (
                            <div className="border-t border-slate-200 px-4 py-3 flex items-center justify-between">
                                <p className="text-xs text-slate-500">
                                    Showing {resumes.from ?? 0}-{resumes.to ?? 0} of {resumes.total ?? 0}
                                </p>
                                <div className="flex gap-1">
                                    {resumes.links?.filter(l => l.url).map((link, i) => (
                                        <Link
                                            key={i}
                                            href={link.url}
                                            className={`px-3 py-1 rounded text-xs font-medium transition-colors ${
                                                link.active
                                                    ? 'bg-blue-600 text-white'
                                                    : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                                            }`}
            dangerouslySetInnerHTML={{ __html: link.label }}
                                        />
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Stats summary */}
                    <div className="mt-6 grid grid-cols-1 sm:grid-cols-3 gap-4">
                        <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
                            <p className="text-xs text-slate-500">Total Generated</p>
                            <p className="text-2xl font-bold text-slate-900">{resumes?.total ?? 0}</p>
                        </div>
                        <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
                            <p className="text-xs text-slate-500">Seekers Without Resume</p>
                            <p className="text-2xl font-bold text-amber-600">{jobSeekersWithoutResume?.length ?? 0}</p>
                        </div>
                        <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
                            <p className="text-xs text-slate-500">Available Templates</p>
                            <p className="text-2xl font-bold text-blue-600">{Object.keys(templates ?? {}).length}</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Generate Modal */}
            {showGenerateModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
                    <div className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl mx-4">
                        <div className="flex items-center justify-between mb-4">
                            <h3 className="text-lg font-semibold text-slate-900">Generate Resume</h3>
                            <button onClick={() => { setShowGenerateModal(false); setSelectedSeekerId(''); }} className="p-1 rounded-lg hover:bg-slate-100">
                                <XCircle className="h-5 w-5 text-slate-400" />
                            </button>
                        </div>
                        <form onSubmit={handleGenerate}>
                            <div className="mb-4">
                                <label className="block text-sm font-medium text-slate-700 mb-1">Select Job Seeker</label>
                                <select
                                    value={selectedSeekerId}
                                    onChange={(e) => setSelectedSeekerId(e.target.value)}
                                    className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
                                    required
                                >
                                    <option value="">-- Select Job Seeker --</option>
                                    {jobSeekersWithoutResume?.map(seeker => (
                                        <option key={seeker.id} value={seeker.id}>
                                            {seeker.first_name} {seeker.last_name} ({seeker.email})
                                        </option>
                                    ))}
                                </select>
                                {(!jobSeekersWithoutResume || jobSeekersWithoutResume.length === 0) && (
                                    <p className="mt-2 text-xs text-amber-600">All fully registered job seekers already have a resume.</p>
                                )}
                            </div>
                            <div className="flex justify-end gap-3">
                                <button
                                    type="button"
                                    onClick={() => { setShowGenerateModal(false); setSelectedSeekerId(''); }}
                                    className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    disabled={!selectedSeekerId || generating}
                                    className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    {generating ? 'Generating...' : 'Generate'}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </AdminLayouts>
    );
}
